# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Estefanía Fernández Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username:  estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Estefania and I am a Master in Software Engineering and Technology and Technical Engineering in Computer Management. 

  I am a passionate about software quality, most of all about <mark>Selenium Webdriver</mark>, 
  <mark>Appium</mark>, <mark>Cypress</mark> or any other tool for Automation Testing.

  Few things about me:

    - Significant QA Engineer and Automation experience (Selenium Webdriver, Appium, Cypress).
    - Experience in Manual and Automated Testing for Software Quality Assurance. 
    - First Certificate in English (FCE) and excellent communication skills. 
    - Strong experience working on International Projects. 
    - Proactive, creative, confident, positive, details oriented, and outgoing person. 
    - Good ability to work in teams and adapt well to change. I truly enjoy working as part of a team.

  If you have any question, suggestion or idea, you can write me an e-mail to: <mark>estefafdez@gmail.com</mark> or on my social media profiles.

  Do you prefer booking a time to talk? Book a slot here! [https://estefafdez.youcanbook.me/](https://estefafdez.youcanbook.me/)

  Visit my blog: [https://unaqaenapuros.wordpress.com/](https://unaqaenapuros.wordpress.com/)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: More Information
more_content: |
    Some videos of my live training presentations: 
    
    Cómo empezar a hacer tus pruebas en iOS con Appium - Estefanía Fernández - YouCanBook Me
      - [https://www.youtube.com/watch?v=xLLbVCjUV-8&li](https://www.youtube.com/watch?v=xLLbVCjUV-8&li)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
