# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Estefania Fernandez Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username:  estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Estefania and I am an Automation QA Engineer at YouCanBook.Me 
  working remotely from Seville (Spain).<br>

  I am a passionate about software quality, most of all about <mark>Selenium Webdriver</mark>, 
  <mark>Appium</mark>, <mark>Cypress</mark> or any other tool for Automation Testing.

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in QA and Software Engineering some of my other interests and hobbies are:

   - TV shows 
   - Music
   - Movies

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
