# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Estefanía Fernández Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username:  estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Estefania and I am a Master in Software Engineering and Technology and Technical Engineering in Computer Management. 

  I am a passionate about Software Quality, most of all about <mark>Selenium Webdriver</mark>, 
  <mark>Appium</mark>, <mark>Cypress</mark> or any other tool for Automation Testing.

  Few things about me:

    - ISTQB® Foundation Level (CTFL) certification.
    - Significant QA Engineer and Automation experience (Selenium Webdriver, Appium, Cypress).
    - Experience in Manual and Automated Testing for Software Quality Assurance. 
    - First Certificate in English (FCE) and excellent communication skills. 
    - Strong experience working on International Projects. 
    - Proactive, creative, confident, positive, details oriented, and outgoing person. 
    - Good ability to work in teams and adapt well to change. I truly enjoy working as part of a team.

  If you have any question, suggestion or idea, you can write me an e-mail to: <mark>estefafdez@gmail.com</mark> or on my social media profiles.

  Do you prefer booking a time to talk? Book a slot here! [https://estefafdez.youcanbook.me/](https://estefafdez.youcanbook.me/)

  Visit my blog about Quality Assurance and Automation Testing: [https://unaqaenapuros.wordpress.com/](https://unaqaenapuros.wordpress.com/)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: More Information
more_content: |
    Some videos of my live training sessions: 
    
    Cómo empezar a hacer tus pruebas en iOS con Appium - Estefanía Fernández - Salmorejotech 2019
      - [https://www.youtube.com/watch?v=xLLbVCjUV-8&li](https://www.youtube.com/watch?v=xLLbVCjUV-8&li)
    
    Cómo hacer test automáticos en aplicaciones iOS con Appium - Open South Code 2019
      - [https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171](https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171)
    
    Mujeres en Testing - Northem Quality - October 2020
      - [https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be](https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be)

    Programando se entienden las máquinas - Podcast Aula Software Libre
      - https://www.uco.es/aulasoftwarelibre/2743-episodio-2-estefania-fernandez-munoz/

# Courses
content:
  - title: Courses
    layout: list
    content: |
    2021: 

      - Automated Visual Testing - A Fast Path To Test Automation Success - Angy Jones
        January 2021
        TAU (Test Automation University)

      - Web Element Locator Strategies - Andrew Knight
        January 2021
        TAU (Test Automation University)

    2020:

      - Introduction to TestNG - Rex Jones II
        January 2020
        TAU (Test Automation University)

      - Introduction to Cypress - Gil Tayar
        February 2020
        TAU (Test Automation University)

      - Selenium WebDriver with Java - Angy Jones
        September 2020
        TAU (Test Automation University)

      - IntelliJ for Test Automation Engineers - Corina Pip
        September 2020
        TAU (Test Automation University)

      - Java Programming - Angy Jones
        September 2020
        TAU (Test Automation University)

      - Modern Functional Test Automation Through Visual AI - Raja Rao DV
        September 2020
        TAU (Test Automation University)

      - Automated Visual Testing with Appium - Jonathan Lipps
        September 2020
        TAU (Test Automation University)

      - Source Control for Test Automation with Git - Simon Berner
        September 2020
        TAU (Test Automation University)

      - Setting a Foundation for Successful Test Automation - Angy Jones
        January 2020
        TAU (Test Automation University)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
