# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Estefanía Fernández Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username: estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez
medium_username: estefafdez

# Theme config
# (Classic method: do NOT use 'content:' or 'version: 2')
theme_config:
  sections:
    - about
    - education
    - experience
    - projects

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
