# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Estefanía Fernández Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username: estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Estefania and I am a Master in Software Engineering and Technology and Technical Engineering in Computer Management. 

  I am a passionate about Software Quality, most of all about <mark>Selenium Webdriver</mark>, 
  <mark>Appium</mark>, <mark>Cypress</mark> or any other tool for Automation Testing.

  Few things about me:
    - Cypress Ambassador
    - ISTQB® Foundation Level (CTFL) certification.
    - Significant QA Engineer and Automation experience (Selenium Webdriver, Appium, Cypress).
    - Experience in Manual and Automated Testing for Software Quality Assurance. 
    - First Certificate in English (FCE) and excellent communication skills. 
    - Strong experience working on International Projects. 
    - Proactive, creative, confident, positive, details oriented, and outgoing person. 
    - Good ability to work in teams and adapt well to change. I truly enjoy working as part of a team.

  If you have any question, suggestion or idea, you can write me an e-mail to: <mark>estefafdez@gmail.com</mark> or on my social media profiles.

  Do you prefer booking a time to talk? Book a slot here! [https://estefafdez.youcanbook.me/](https://estefafdez.youcanbook.me/)

  Visit my blog about Quality Assurance and Automation Testing: [https://unaqaenapuros.wordpress.com/](https://unaqaenapuros.wordpress.com/)

content:
  # Projects Section
  - title: Projects Section
  - layout: left
    name: Una QA En Apuros (Blog)
    link: https://unaqaenapuros.wordpress.com/
    description: |
      Creation of the blog “Una QA en Apuros” on Wordpress where I published articles related with the software quality focus on the automation testing open source tools such as Appium, Selenium or Cypress. 
      Also you can find articles about CI/CD tools such as Jenkins.

  - layout: left
    name: Appium Native Java Example
    link: https://github.com/estefafdez/appium-native-java-example
    description: |
      Example on iOS and Android using Appium. The aim of this project is provide a maven project in order to run automated test with Android and iOS easily.

  - layout: left
    name: cypress-template
    link: https://github.com/estefafdez/cypress-template
    description: |
      Example of a real project based in Cypress with Page Object Model Implemented, API Tests, Github Actions and SonarCloud included.

  - layout: left
    name: cypress-testrail-all-status plugin
    link: https://www.npmjs.com/package/cypress-testrail-all-status
    description: |
      cypress-testrail-all-status plugin on NPM for publishing your Cypress Tests Results on TestRail.

  - layout: left
    name: selenium-template
    link: https://github.com/estefafdez/selenium-template
    description: |
      Example of a real project based in Selenium with Page Object Model Implemented and Travis CI.

  - layout: left
    name: Selenium Pipeline on Jenkins
    link: https://github.com/estefafdez/selenium-pipeline
    description: |
      Run your Selenium Test easily using this declarative pipeline on Jenkins.

  - layout: left
    name: Barista Android App
    link: https://github.com/estefafdez/AndroidBaristaProject
    description: |
      A simple Android App along with Barista for Testing Purposes.

  - layout: left
    name: iOS Test App
    link: https://github.com/estefafdez/iOSTestApp
    description: |
      A simple iOS App with Swift and Xcode 8 for Testing Purposes.

  - layout: left
    name: Selenium Cucumber Project
    link: https://github.com/estefafdez/selenium-cucumber/
    description: |
      This project is a Selenium Webdriver 3.0.1 integration with Cucumber on Java and include several features, such as:

      - Choose your OS, Browser and Log Level on the POM: On the pom.xml file you can choose between: Several OS: Windows, Mac, Linux, several Browsers: Chrome, Firefox, IE and several log level configuration: All, Debug, Info, Warn, Error, Fatal, Off.

      - Step Definition By Action: On this project you can find the following set of predefined steps ordered by action already done for you. The types of actions are: Assertion Steps, Click Steps, Configuration Steps, Input Steps...

      - SonarQube included: In order to maintain the quality of your code and your project, SonarQube is included on this repository, also the instruction to run SonarQube on Docker easily.

      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Experience Section
  - title: Experience Section
  - layout: left
    company: Genially
    link: https://genial.ly/
    job_title: Remote. QA Engineer Manager
    dates: January 2021 - Present
    quote: >
      Creating interactive content is WOW!
    description: |
      Creation and setting up the QA bases on the company. Define the QA strategy. Create the CI/CD model using Docker, K8 and Jenkins.

      **Main responsibilities:** QA project management and leadership: define strategy on the quality bases for the company, estimation and planning. Design and creation of automated tests: E2E and API testing using Cypress. Manage the team: currently 6 people. 

      **Technologies:** GitHub, TestRail, TypeScript, Javascript, Cypress, React Test Library, Jenkins, K8, Lens.

  - layout: left
    company: YouCanBook.Me
    link: https://youcanbook.me/
    job_title: Remote. QA Automation Engineer
    dates: April 2019 - December 2020.
    quote: >
      Tiny Company that does Big Things
    description: |
      Working on a small team to do great things remotely. Creation and setting up the QA bases on the company. Define the QA strategy. Create the CI/CD model using Docker, Terraform and AWS (Code Build).

      **Main responsibilities:** QA project management and leadership: define strategy on the quality bases for the company, estimation and planning. Design and creation of automated tests: E2E and API testing using Selenium and Cypress.

      **Technologies:** Jira, TestRail, Java, Javascript, Cypress, Selenium, Maven, React Test Library, TestNG, Junit, Postman, CodeBuild, CodePipeline, Terraform.

  - layout: left
    company: SDOS
    link: https://sdos.es/
    job_title: Head of QA / DevOps.
    dates: June 2017 – April 2019
    quote: >
      #somosEquipo
    description: |
      Creation and setting up the QA Department. Define the QA strategy. Create the CI/CD model using Jenkins and Docker. Featured Project: Android app development for the El Corte Ingles, Inditex, and Android/iOS development of Prisa Group and CCMA (Corporación Catalana de Medios Audiovisuales).

      **Main responsibilities:** QA Team management and leadership: currently 7 people, estimation and planning, design and creation of the Selenium and Appium Core for SDOS, Quality Lead, creation, development and maintenance of the CD/CI Structure for Android and QA using pipelines along with Jenkins. 

      **Technologies:** RedMine, Jira, TestRail, Jira, Java, Drupal, Android Development, iOS development, Jenkins, Sonar, Artifactory / Nexus, Selenium, Appium, TestNG, JUnit, Jmeter, MobSF, Docker, Kubernetes, Wiremock, Continuous Integration, Continuous Deployment, Declarative Pipelines, Jenkinsfile

  - layout: left
    company: Ontech Advanced Technology
    link: https://www.ontech.es/
    job_title: Senior QA Engineer
    dates: February 2017 – June 2017
    description: |
      Wardiam Pro Project. The function performed are: Design of Functional Test for the Alarm system Wardiam Pro on TestLink and RedMine,
      Manual Test execution of software, hardware and firmware test on the following Wardiam Pro devices: Wardiam Center, Wardiam Sensor, Wardiam Camera, Wardiam Hooter and Wardiam Tag on Testlink and Redmine.
      Design and execution of functional testing for other I+D project developed with the Controlled Magnetic Fields (CMF) technology. Detection, report and tracking of issues: software, hardware or firmware using Redmine.
      Firmware load on the devices using Microchip. Bug fixing on logs.

  - layout: left
    company: Emergya Ingeniería S.L. Drupalera.
    link: https://www.emergya.com/es
    job_title: Senior QA Engineer / QA Lead.
    dates: June 2016 – January 2017
    description: |
      izi.TRAVEL project at Emergya. The function performed are: Creation, development and maintenance of the Manual Test Plan on TestRail, creation, development and maintenance of the Automation Test Plan on TestRail. 
      Creation, development and maintenance of the Responsive Manual Test Plan on TestRail. 
      Manual Test execution of Regression Test Plan with TestRail. 
      Automation test development in Java using Selenium WebDriver, Jenkins, TestNG, Maven. 
      Running Automated test on remote using SauceLabs. 
      Detection, report and tracking of issues using Jira. 
      Reviewing and document results, and reporting incidents to the development team to ensure Software Quality. 
      Continuous Integration using Jenkins and Docker on Linux. Definition of the scope for the next release along with the Product Owner and the client. 
      Performance Testing with JMeter and integration with Jenkins. 
      Agile methodology: Scrum.

  - layout: left
    company: Atos Global
    link: https://atos.net/en/
    job_title: QA Department. Junior QA Engineer.
    dates: February 2015- June 2016
    description: |
      BlueKiwi Enterprise Social Networking. 
      The functions performed are: Develop automated test on Java (using Selenium WebDriver) for the non-regression testing on Bluekiwi. 
      Implement process using the Jenkins continuous integration tool for automatic deployment of applications in different environments. 
      Manual test execution of Regression Test Plan with Jira. 
      Detection, report and tracking of issues using Jira. 
      Modification and improvement of the Test Plan. Reviewing and document results, and reporting incidents to the development team to ensure Software Quality. 
      Agile methodology: Scrum.

  - layout: left
    company: Admiral Group Ltd (Balumba y Qualitas Auto)
    link: https://admiralgroup.co.uk/
    job_title: QA Department. QA Assistant
    dates: June 2014- December 2014
    description: |
      Motorcycles project as a new line of business in Admiral Spain. 
      The functions performed were: Develop automated test Java (Selenium WebDriver) with access to Oracle database. 
      Implement process using the Jenkins continuous integration tool for automatic deployment of applications in different environments. 
      Reviewing and document results, and reporting incidents to the development team to ensure software quality. 
      Tools and technologies used: Java, WebDriver (Selenium), JUnit, TestNG, TestLink, Jenkins.

      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Education Section
  - title: Education Section
  - layout: top-middle
    name: Master in Software Engineering and Technology
    dates: 2013 - 2014
    qualification: University of Seville

  - layout: top-middle
    name: Technical Engineer of Computer Science Management
    dates: 2005 - 2012
    qualification: University of Córdoba

  - layout: top-middle
    name: Erasmus Scholarship
    dates: 2011 - 2011
    qualification: Technicka Univerzita Ostrava (Vysoká škola Báňská), Czech Republic

  # Aditional training

  - layout: top-middle
    name: ISTQB Foundation Level
    dates: July 2018.
    qualification: ISTQB - International Software Testing Qualifications Board

  - layout: top-middle
    name: Scrum Manager
    dates: November 2017.
    qualification: Scrum Manager. ID 15465.

  - layout: top-middle
    name: Cambridge English First (FCE)
    dates: January 2014.
    qualification: Cambridge University

  - layout: top-middle
    name: Advanced Kubernetes Training
    dates: 20 hours. May 2018.
    qualification: Bitnami

  # More Section
  - title: More Information
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some videos of my live training sessions: 

      Cómo empezar a hacer tus pruebas en iOS con Appium - Estefanía Fernández - Salmorejotech 2019
      - [https://www.youtube.com/watch?v=xLLbVCjUV-8&li](https://www.youtube.com/watch?v=xLLbVCjUV-8&li)

      Cómo hacer test automáticos en aplicaciones iOS con Appium - Open South Code 2019
      - [https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171](https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171)

      Mujeres en Testing - Northem Quality - October 2020
      - [https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be](https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be)

      Programando se entienden las máquinas - Podcast Aula Software Libre December 2020
      - [https://www.uco.es/aulasoftwarelibre/2743-episodio-2-estefania-fernandez-munoz/](https://www.uco.es/aulasoftwarelibre/2743-episodio-2-estefania-fernandez-munoz/)

      Automatización de Pruebas: República Web #208 with Manuel Franco - June 2022
      - [https://www.youtube.com/watch?v=BEN2t_DXEB4](https://www.youtube.com/watch?v=BEN2t_DXEB4)

      ¿Qué es el rol de QA tester en Programación? | #laFunción 8x17 - Codely February 2023
      - [https://www.youtube.com/watch?v=vbNbfBE2D7s](https://www.youtube.com/watch?v=vbNbfBE2D7s)

      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

      Courses over the years: 

      2022:

      - Cypress Ambassador 
        June 2022.

      - Introducción a Figma y diseño de interfaces - Carlos Andres Orozco Palacio
        June 2022. 
        Código Facilito.

      - How to Manage a Remote Team by the GitLab team.
        May 2022.
        Coursera.

      2021: 

        - Automated Visual Testing - A Fast Path To Test Automation Success - Angy Jones.
          January 2021.
          TAU (Test Automation University).

        - Web Element Locator Strategies - Andrew Knight.
          January 2021.
          TAU (Test Automation University).

        - Cucumber with Java - Giridhar Rajkumar.
          January 2021.
          TAU (Test Automation University).

      2020:

        - Introduction to TestNG - Rex Jones II.
          January 2020.
          TAU (Test Automation University).

        - Introduction to Cypress - Gil Tayar.
          February 2020.
          TAU (Test Automation University).
        
        - Test Automation- quick start - Rostyslav Apostol.
          April 2020.
          Udemy.

        - Web Application Performance Testing - Mentors Native.
          April 2020.
          Udemy.  

        - Test Driven Development con Java y Junit5 - Alejandro Polo Rangel.
          April 2020.
          Udemy.

        - Selenium WebDriver with Java - Angy Jones.
          September 2020.
          TAU (Test Automation University).

        - IntelliJ for Test Automation Engineers - Corina Pip.
          September 2020.
          TAU (Test Automation University).

        - Java Programming - Angy Jones.
          September 2020.
          TAU (Test Automation University).

        - Modern Functional Test Automation Through Visual AI - Raja Rao DV.
          September 2020.
          TAU (Test Automation University).

        - Automated Visual Testing with Appium - Jonathan Lipps.
          September 2020.
          TAU (Test Automation University).

        - Source Control for Test Automation with Git - Simon Berner.
          September 2020.
          TAU (Test Automation University).

        - Setting a Foundation for Successful Test Automation - Angy Jones.
          January 2020.
          TAU (Test Automation University).

      2019: 

        - CP-SAT - Certified Professional Selenium Automation Testing - Agile Testing Alliance Org. 
          February 2019.
          Udemy.

        - Accessibility Features on Android. 
          February 2019.
          Udemy.

        - Jenkins Introduction for Developer - Tan Pham.
          February 2019.
          Udemy.

        - CICD (DevOPs Tools) for Automation Testers (Selenium) - Automation Talks.
          February 2019.
          Udemy.

        - Making Chatbot & Voice Apps (with Dialogflow v1) - M.Inzamam Malik.
          February 2019.
          Udemy. 

        - Automation Testing With HP UFT 14.00 Latest Version - Pavan Lalwani.
          April 2019.
          Udemy. 

        - Everything for Software Tester - Testing World.
          April 2019.
          Udemy. 

        - Software Testing By Innovation Techniques - Ganesh Sahai.
          May 2019.
          Udemy. 

        - Build+Deploy+Test with Jenkins 2.0 - Karthik KK.
          June 2019.
          Udemy.

      2018: 

        - Kubernetes Course from a DevOps guru (Kubernetes + Docker).
          December 2018.
          Udemy.

        - Selenium WebDriver with C# for Beginners + Live Testing Site - Tod Vachev.
          December 2018.
          Udemy. 

        - Learn DevOps with Jenkins All in One Guide - Eduonix Learning Solutions.
          December 2018.
          Udemy.

        - Software Testing.
          December 2018.
          Udemy. 

        - Learn Manual Testing:basics for beginners - Naveen Kumar A.
          December 2018.
          Udemy.

      2017:

        - Automated Business Readable Web Tests with Selenium and SpecFlow. 
          January 2017.
          Pluralsight.

        - Automated Web Testing with Selenium. 4h. 
          February 2017.
          Pluralsight.

        - Docker Deep Dive. 
          February 2017.
          Pluralsight.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
