# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Estefanía Fernández Muñoz
title: Technical Engineering in Computer Management. Master in Software Engineering and Technology. Automation QA Engineer.
email: estefafdez@gmail.com
website: https://unaqaenapuros.wordpress.com/

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: estefafdez
github_username: estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, My name is Estefania and I am a Master in Software Engineering and Technology and Technical Engineering in Computer Management. 

  I am a passionate about Software Quality, most of all about <mark>Selenium Webdriver</mark>, 
  <mark>Appium</mark>, <mark>Cypress</mark> or any other tool for Automation Testing.

  Few things about me:
    - Cypress Ambassador
    - ISTQB® Foundation Level (CTFL) certification.
    - Significant QA Engineer and Automation experience (Selenium Webdriver, Appium, Cypress).
    - Experience in Manual and Automated Testing for Software Quality Assurance. 
    - First Certificate in English (FCE) and excellent communication skills. 
    - Strong experience working on International Projects. 
    - Proactive, creative, confident, positive, details oriented, and outgoing person. 
    - Good ability to work in teams and adapt well to change. I truly enjoy working as part of a team.

  If you have any question, suggestion or idea, you can write me an e-mail to: <mark>estefafdez@gmail.com</mark> or on my social media profiles.

  Do you prefer booking a time to talk? Book a slot here! [https://estefafdez.youcanbook.me/](https://estefafdez.youcanbook.me/)

  Visit my blog about Quality Assurance and Automation Testing: [https://unaqaenapuros.wordpress.com/](https://unaqaenapuros.wordpress.com/)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

content:
  # More Section
  - title: More Information
    layout: text
    content: | # this will include new lines to allow paragraphs
      Some videos of my live training sessions: 

      Cómo empezar a hacer tus pruebas en iOS con Appium - Estefanía Fernández - Salmorejotech 2019
      - [https://www.youtube.com/watch?v=xLLbVCjUV-8&li](https://www.youtube.com/watch?v=xLLbVCjUV-8&li)

      Cómo hacer test automáticos en aplicaciones iOS con Appium - Open South Code 2019
      - [https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171](https://www.opensouthcode.org/conferences/opensouthcode2019/program/proposals/171)

      Mujeres en Testing - Northem Quality - October 2020
      - [https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be](https://www.youtube.com/watch?v=jsU059nMYUo&feature=youtu.be)

      Programando se entienden las máquinas - Podcast Aula Software Libre December 2020
      - [https://www.uco.es/aulasoftwarelibre/2743-episodio-2-estefania-fernandez-munoz/](https://www.uco.es/aulasoftwarelibre/2743-episodio-2-estefania-fernandez-munoz/)

      Automatización de Pruebas: República Web #208 with Manuel Franco - June 2022
      - [https://www.youtube.com/watch?v=BEN2t_DXEB4](https://www.youtube.com/watch?v=BEN2t_DXEB4)

      cypress-testrail-all-status plugin on NPM for publishing your Cypress Tests Results on TestRail. 
      - [https://www.npmjs.com/package/cypress-testrail-all-status](https://www.npmjs.com/package/cypress-testrail-all-status)

      - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

      Courses over the years: 

      2022:

      - Cypress Ambassador 
        June 2022.

      - Introducción a Figma y diseño de interfaces - Carlos Andres Orozco Palacio
        June 2022. 
        Código Facilito.

      - How to Manage a Remote Team by the GitLab team.
        May 2022.
        Coursera.

      2021: 

        - Automated Visual Testing - A Fast Path To Test Automation Success - Angy Jones.
          January 2021.
          TAU (Test Automation University).

        - Web Element Locator Strategies - Andrew Knight.
          January 2021.
          TAU (Test Automation University).

        - Cucumber with Java - Giridhar Rajkumar.
          January 2021.
          TAU (Test Automation University).

      2020:

        - Introduction to TestNG - Rex Jones II.
          January 2020.
          TAU (Test Automation University).

        - Introduction to Cypress - Gil Tayar.
          February 2020.
          TAU (Test Automation University).
        
        - Test Automation- quick start - Rostyslav Apostol.
          April 2020.
          Udemy.

        - Web Application Performance Testing - Mentors Native.
          April 2020.
          Udemy.  

        - Test Driven Development con Java y Junit5 - Alejandro Polo Rangel.
          April 2020.
          Udemy.

        - Selenium WebDriver with Java - Angy Jones.
          September 2020.
          TAU (Test Automation University).

        - IntelliJ for Test Automation Engineers - Corina Pip.
          September 2020.
          TAU (Test Automation University).

        - Java Programming - Angy Jones.
          September 2020.
          TAU (Test Automation University).

        - Modern Functional Test Automation Through Visual AI - Raja Rao DV.
          September 2020.
          TAU (Test Automation University).

        - Automated Visual Testing with Appium - Jonathan Lipps.
          September 2020.
          TAU (Test Automation University).

        - Source Control for Test Automation with Git - Simon Berner.
          September 2020.
          TAU (Test Automation University).

        - Setting a Foundation for Successful Test Automation - Angy Jones.
          January 2020.
          TAU (Test Automation University).

      2019: 

        - CP-SAT - Certified Professional Selenium Automation Testing - Agile Testing Alliance Org. 
          February 2019.
          Udemy.

        - Accessibility Features on Android. 
          February 2019.
          Udemy.

        - Jenkins Introduction for Developer - Tan Pham.
          February 2019.
          Udemy.

        - CICD (DevOPs Tools) for Automation Testers (Selenium) - Automation Talks.
          February 2019.
          Udemy.

        - Making Chatbot & Voice Apps (with Dialogflow v1) - M.Inzamam Malik.
          February 2019.
          Udemy. 

        - Automation Testing With HP UFT 14.00 Latest Version - Pavan Lalwani.
          April 2019.
          Udemy. 

        - Everything for Software Tester - Testing World.
          April 2019.
          Udemy. 

        - Software Testing By Innovation Techniques - Ganesh Sahai.
          May 2019.
          Udemy. 

        - Build+Deploy+Test with Jenkins 2.0 - Karthik KK.
          June 2019.
          Udemy.

      2018: 

        - Kubernetes Course from a DevOps guru (Kubernetes + Docker).
          December 2018.
          Udemy.

        - Selenium WebDriver with C# for Beginners + Live Testing Site - Tod Vachev.
          December 2018.
          Udemy. 

        - Learn DevOps with Jenkins All in One Guide - Eduonix Learning Solutions.
          December 2018.
          Udemy.

        - Software Testing.
          December 2018.
          Udemy. 

        - Learn Manual Testing:basics for beginners - Naveen Kumar A.
          December 2018.
          Udemy.

      2017:

        - Automated Business Readable Web Tests with Selenium and SpecFlow. 
          January 2017.
          Pluralsight.

        - Automated Web Testing with Selenium. 4h. 
          February 2017.
          Pluralsight.

        - Docker Deep Dive. 
          February 2017.
          Pluralsight.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
