# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Estefanía Fernández Muñoz
title: Automation QA Engineer
email: estefafdez@gmail.com
website: https://estefafdez.github.io/
blog: https://unaqaenapuros.wordpress.com/

# Social links
twitter_username: estefafdez
github_username:  estefafdez
instagram_username: estefafdez
linkedin_username: estefafdez
youtube_username: estefafdez

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
- Hello, My name is Estefania and I am an Automation QA Engineer at YouCanBook.Me working remotely from Seville (Spain). 

- I am a passionate about software quality, most of all about Selenium Webdriver, Appium, Cypress or any other tool for Automation Testing.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - TV Shows
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
